# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Thanks for opening your first issue here! Be sure to follow the issue template for [bug report](https://github.com/LiskHQ/lisk-hub/blob/development/.github/ISSUE_TEMPLATE/bug_report.md) or [feature request](https://github.com/LiskHQ/lisk-hub/blob/development/.github/ISSUE_TEMPLATE/feature_request.md)!

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Thanks for opening this pull request! Please check out our [contributing guidelines](https://github.com/LiskHQ/lisk-hub/blob/development/CONTRIBUTING.md).

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on merging your first pull request! Ready for new challenges? You can find your next issue [here](https://github.com/LiskHQ/lisk-hub/issues)

# It is recommend to include as many gifs and emojis as possible
