dist: 'trusty'
language: java
jdk:
  - oraclejdk8
env:
  - NODE_VERSION=6.10.1
cache:
  directories:
    - src/node_modules/
services:
  - postgresql
addons:
  postgresql: '9.6'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cd src
install:
  - nvm install $NODE_VERSION
  - npm install
before_script:
  - ../.travis/before_script.sh
 - ./node_modules/protractor/bin/webdriver-manager update
script:
  - nvm use $NODE_VERSION
  - npm run test
  - npm run dev &> .lisk-nano.log &
  - sleep 20
  - npm run e2e-test
after_script:
  - cat .protractor.log
  - cat .lisk-core.log
  - cat .lisk-nano.log
